### ISSUE TITLE
[Account Temporarily Blocked]

### ISSUE THREAD

**Issue by zoo911** [anoduck/UFS-quackified#5]
### How far did you get into the scraping process before you account was blocked?

Wasn't necessarily blocked, but got caught into "Verify your info" every single time I had to sign in.

### How many profiles did the script traverse before getting blocked?

0

#### Did you modify the script?

Yes

#### If so, What vales did you enter for the rate limit variables and for the time sleep variables.

I entered a 90 second sleep after login and it gave me enough time to "verify myself" via email

#### What is the version of chrome driver that you are using?

79

#### What Operating System are you running?

Linux

#### Did you notify facebook that there restrictions were too hight?

Yes.

I'm going to try mobile.fb.com because even after going through your script, I was being rate limited like "You've been using this feature too much" not even going through 1 profile.

**Comment by anoduck** [comment]
Hmmm... have not seen that one before.

Are you getting the same error to verify your profile without using the script, I.E. just using a normal browser?

Are you attempting to use a proxy or tor effecting the geographical location where you would normally log in from? 

Why or what were the reasons you had to log in more than once or twice? 

What flavor of linux are you using?

You might run into difficulties using the mobile site. Depending on which user agent you decide to use the links and xpaths used for scraping may change. This occurs when attempting to use the user agent for the Facebook app on iPhone for example. I did not notice any difference in how the script interacted with facebook using the mobile site for android. But, you might discover something different. 

Also, you might consider further extending the length of the scraping process. 

I will test the script tonight and see if I encounter a similar limitation.

**Comment by anoduck** [comment]
The test is running and so far so good. No hicups or bumps...

You might want to let things cool off for a few days and try again. The multiple logins with the same user agent moving at the same pace might have placed your account on a watch list for security purposes.
