### ISSUE TITLE
webdriver_manager is missing from requirements.txt

### ISSUE THREAD

**Issue by NekoShinobi** [anoduck/UFS-quackified#6]
I don't know if this is unique to me, but webdriver_manger was missing.
I installed `webdriver_manager` and it worked fine after that.

I'm using Manjaro Linux w/ latest master code.

**Comment by anoduck** [comment]
Glad you got it working. Webdriver Manager was and is disabled in future versions. Users are expected to maintain their own distribution of chromedriver whatever that is. 

I will make a note to implement a configuration file in the next release, to ease users in configuring the script to their systems.
