### ISSUE TITLE
Blank output. Errors like: No Exception (save_to_file) Status = 3 <class 'IndexError'>

### ISSUE THREAD

**Issue by aguhob** [anoduck/UFS-quackified#7]
I cloned and ran the code as is, after adjusting credentials.txt and input.txt. 
I saw ChromeDriver running through the correct FB profile (a group). 
But nothing got scraped. I got a blank Posts.txt file.
 
Got errors  "Exception (save_to_file) Status = 3 <class 'IndexError'>" which I usually see when I've been blocked, but it was my first scrape of the week.  

 - OS: MacOS 10.14.6
 - Python version 3.6.3
 - Version b765b6e

Scraping: https://www.facebook.com/groupname

Scraping Friends..
Exception (scrape_data) 0 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 2 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 3 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 4 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 5 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 6 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 7 Status = 0 <class 'selenium.common.exceptions.NoSuchElementException'>
Friends Done!

Scraping Photos..
Exception (scrape_data) 0 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 1 <class 'selenium.common.exceptions.NoSuchElementException'>
Photos Done!

Scraping Videos..
Exception (scrape_data) 0 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Exception (scrape_data) 1 Status = 2 <class 'selenium.common.exceptions.NoSuchElementException'>
Videos Done!

Scraping About..
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
Exception (save_to_file) Status = 3 <class 'IndexError'>
About Done!

Scraping Posts..
Posts Done!

**Comment by anoduck** [comment]
Just from looking at the reported errors, it appears you attempted to run the script after the book of face had performed its interface overhaul, meaning that the script was attempting to reference elements that were no longer a part of the document being scraped. This should be fixed in the next update. 

Also worth noting, the script is not intended to scrape groups but profiles.
